### ISSUE TITLE
error when same contributor placed several orders

### ISSUE THREAD

**Issue by aduermael** [aduermael/ulule-supporters#1]
One contributor ordered same pack 7 times, only one got exported.

**Comment by Pierstoval** [comment]
On Ulule, the export should say `x7` in one column, have you checked all the details of the API?

**Comment by aduermael** [comment]
@Pierstoval I should certainly close that issue for now. I used to have more use cases on that repo in the past but cleanup up to make it public. Actually the only tool available is for the lottery, it's been tested and shows same numbers as on Ulule (for Laurel's `comme-convenu-2` project at least).

**Comment by Pierstoval** [comment]
I'll have to make a test for one of @StudioAgate's campaigns :)

**Comment by aduermael** [comment]
Oh, I would love to get feedback if you do! 🙂
So far, I've only been using the API client with 2 projects (`comme-convenu` & `comme-convenu-2`)
